"""
Django settings for amud_site project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# Every setting below reads from an env var first so the same settings.py
# serves local dev (no env vars set, defaults match the old hardcoded
# values) and production (all of these set on the deploy target) — see
# web/README.md for the full env var list.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-q12jeilgtnsa#xuig(oa1_zx0ne+3-hci1x#mtj+gbe+^v4e(a',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o
]


def _ec2_private_ip() -> str | None:
    """The ALB's health check hits the instance directly using its private
    IP as the Host header, not one of the real domains — without this,
    every health check 400s on ALLOWED_HOSTS and the environment reports
    permanently unhealthy even though real traffic works fine. IMDSv2 only
    (this account's instances require the token). Times out fast and
    returns None off-EC2 (local dev, Docker build) rather than hanging.
    """
    try:
        import httpx

        token = httpx.put(
            'http://169.254.169.254/latest/api/token',
            headers={'X-aws-ec2-metadata-token-ttl-seconds': '21600'},
            timeout=0.5,
        ).text
        return httpx.get(
            'http://169.254.169.254/latest/meta-data/local-ipv4',
            headers={'X-aws-ec2-metadata-token': token},
            timeout=0.5,
        ).text.strip()
    except Exception:
        return None


if not DEBUG:
    ec2_private_ip = _ec2_private_ip()
    if ec2_private_ip:
        ALLOWED_HOSTS.append(ec2_private_ip)

    # The HTTP->HTTPS redirect happens at the load balancer, not here:
    # Elastic Beanstalk's per-instance nginx sits between the ALB and this
    # app and isn't guaranteed to forward the ALB's real X-Forwarded-Proto
    # untouched (a known EB quirk) — if it overwrites it to "http", Django
    # doing its own SECURE_SSL_REDIRECT would 301-loop forever on every
    # request. Secure cookies don't have that failure mode (they just mark
    # the cookie, they don't redirect), so those stay on unconditionally.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Trusting X-Forwarded-Proto here carries none of the SECURE_SSL_REDIRECT
    # loop risk above — it only affects request.scheme/is_secure(), which
    # canonical/og:url/og:image/schema.org URLs in base.html read. Without
    # this, Django sees the plain-HTTP ALB->instance hop and every one of
    # those URLs renders as http:// even though the site is HTTPS-only,
    # splitting the indexing signal between two schemes.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'judicial_deposits',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amud_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amud_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Postgres here is the "system's own transactional tables" half of the
# serving layer (CLAUDE.md) — Django's own auth/session/admin tables, not
# the marts tables, which don't exist yet (Phase 6 is deferred). Falls back
# to sqlite when DB_HOST isn't set, so local dev is unaffected.

if os.environ.get('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ['DB_HOST'],
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Served straight out of the app container by whitenoise — no separate
# static host needed at this traffic scale.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# judicial_deposits document-number search — local read cache of core/ Parquet, synced
# from S3 by `python manage.py sync_core_cache`. Not a marts table (Phase
# 6/marts is still deferred, see project-context.md §7): this recomputes the
# same per-party aggregation at query time straight off `core`, just against
# a local copy instead of live S3. A point query against the real bucket
# takes 15-50s — the Parquet isn't partitioned by party_id, so a filtered
# read range-scans most of the file over HTTP; the same query against a
# local copy is sub-100ms.
CLAIMS_ENGINE_BUCKET = os.environ.get('CLAIMS_ENGINE_BUCKET', 'amud-technologies')
CORE_CACHE_DIR = BASE_DIR / 'var' / 'core_cache'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
