# Generated by Django 6.1 on 2026-08-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g. 2026-1', max_length=16, unique=True)),
                ('opens_on', models.DateField(blank=True, null=True)),
                ('closes_on', models.DateField()),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
    ]
